version: '3'
services: 
    front: 
        build: .
        volumes: 
          - .:/usr/src/app
          - /usr/src/app/node_modules/
        ports:
          - 3000:3000
        command: npm start
networks:
  default:
    external:
      name: mytrainer-app

